### PR TITLE
Add node_type to replace is_producer

### PR DESCRIPTION
**Pull request by xebb82**
This way we open for the possibility to have specific query nodes and other things we might need in the future.

### CODE REVIEW

**Comment by matthewdarwin** [comment]
The is_producer should be removed at the same time as adding node_type.  Having both is confusing.   

Also I'm not really sure what is the point of this.  BPs should only document their public nodes.... the actual producer nodes should be hidden and not publicly documented anywhere.

**Comment by eosrio** [comment]
Leaving is_producer is good for backwards compatibility, but should be marked a deprecated in favor of node_type. Listing producer nodes might be useful for location purposes since scheduling will depend on that.

**Comment by DenisCarriere** [comment]
Updated README document to reflect this schema change.

**Comment by n8d** [comment]
I don't think this is clear. What is the difference between "full" and "query"?

We have been using the terms "producer", "api" and "peer" when communicating about nodes in our infrastructure. Would that work here?

**Pull request merged**
